title: Agile Wiki
description:        Knowledge base Jekyll theme.
permalink:          /:title/
url:                "https://agilewiki.cz"
logo_image:
    light:          logo-light.svg  # e.g. logo.png, upload logo image file to /assets/posts/ folder
    dark:           logo-dark.svg  # e.g. logo.png, upload logo image file to /assets/posts/ folder

# Author settings, displayed on about page
author:
    name: 'Lukáš Bednařík'
    email: 'lukas@lukasbednarik.cz'
    website: 'https://lukasbednarik.cz'
    facebook: https://www.facebook.com/
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/
    linkedin:
    pinterest:
    twitter:        https://twitter.com/
    vimeo:          https://vimeo.com/
    youtube:

# Social share buttons
twitter_username:   ivanchromjak
github_username:    ivanchromjak

# Default footer image settings
footer:
    copyright: 'Podporováno <a href="https://agilecz.cz">českou Agilní komunitou</a>'

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 7865

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  faqs:
    output: false
